# Generated by Django 4.0.5 on 2022-07-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Записи', 'verbose_name_plural': 'Гостевые книги'},
        ),
        migrations.AlterField(
            model_name='article',
            name='authorEmail',
            field=models.EmailField(max_length=50, verbose_name='email автора'),
        ),
    ]
